
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] 
# The modid of the mod
modId="iff" 


version="1.2.1" 

displayName="Invisable Frames for Forge"


logoFile="logo.png" 


authors="acaeaeeda"

description='''Right click the item frame to make it invisible.'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.iff]] #optional
    # the modid of the dependency
    modId="forge"
  
    mandatory=true 
    # The version range of the dependency
    versionRange="[40,)"
    
    ordering="NONE"
    
    side="BOTH"

[[dependencies.iff]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
